import { tr } from "@/i18n/translate"; /**
 * Code generated by cmd/settingsgen from contracts/settings/v1/manifest.json. DO NOT EDIT.
 *
 * Regenerate with: make settings-bindings
 *
 * Every key, type, scope and default here comes from the manifest, so a client
 * cannot drift from the server's contract by editing a constant. Adding a setting
 * is a manifest change plus a regeneration, never a hand-written key.
 */

export const SETTINGS_API_VERSION = 1;
export const SETTINGS_REVISION = 8;

export interface SettingSuggestedOption {
  value: string;
  introducedIn: number;
}

export interface SettingOptionSet {
  type: string;
  options: readonly SettingSuggestedOption[];
}

export const SETTING_OPTION_SETS = {
  catalog_metadata_languages: {
    type: "language_tag",
    options: [
      { value: "ar", introducedIn: 1 },
      { value: "bn", introducedIn: 1 },
      { value: "bg", introducedIn: 1 },
      { value: "zh", introducedIn: 1 },
      { value: "hr", introducedIn: 1 },
      { value: "cs", introducedIn: 1 },
      { value: "da", introducedIn: 1 },
      { value: "nl", introducedIn: 1 },
      { value: "en", introducedIn: 1 },
      { value: "fi", introducedIn: 1 },
      { value: "fr", introducedIn: 1 },
      { value: "de", introducedIn: 1 },
      { value: "el", introducedIn: 1 },
      { value: "he", introducedIn: 1 },
      { value: "hi", introducedIn: 1 },
      { value: "hu", introducedIn: 1 },
      { value: "id", introducedIn: 1 },
      { value: "it", introducedIn: 1 },
      { value: "ja", introducedIn: 1 },
      { value: "ko", introducedIn: 1 },
      { value: "ms", introducedIn: 1 },
      { value: "no", introducedIn: 1 },
      { value: "fa", introducedIn: 1 },
      { value: "pl", introducedIn: 1 },
      { value: "pt", introducedIn: 1 },
      { value: "ro", introducedIn: 1 },
      { value: "ru", introducedIn: 1 },
      { value: "sk", introducedIn: 1 },
      { value: "sl", introducedIn: 1 },
      { value: "es", introducedIn: 1 },
      { value: "sv", introducedIn: 1 },
      { value: "ta", introducedIn: 1 },
      { value: "te", introducedIn: 1 },
      { value: "th", introducedIn: 1 },
      { value: "tr", introducedIn: 1 },
      { value: "uk", introducedIn: 1 },
      { value: "vi", introducedIn: 1 },
    ],
  },
  playback_audio_languages: {
    type: "language_tag",
    options: [
      { value: "ar", introducedIn: 1 },
      { value: "bn", introducedIn: 1 },
      { value: "bg", introducedIn: 1 },
      { value: "zh", introducedIn: 1 },
      { value: "hr", introducedIn: 1 },
      { value: "cs", introducedIn: 1 },
      { value: "da", introducedIn: 1 },
      { value: "nl", introducedIn: 1 },
      { value: "en", introducedIn: 1 },
      { value: "fi", introducedIn: 1 },
      { value: "fr", introducedIn: 1 },
      { value: "de", introducedIn: 1 },
      { value: "el", introducedIn: 1 },
      { value: "he", introducedIn: 1 },
      { value: "hi", introducedIn: 1 },
      { value: "hu", introducedIn: 1 },
      { value: "id", introducedIn: 1 },
      { value: "it", introducedIn: 1 },
      { value: "ja", introducedIn: 1 },
      { value: "ko", introducedIn: 1 },
      { value: "ms", introducedIn: 1 },
      { value: "no", introducedIn: 1 },
      { value: "fa", introducedIn: 1 },
      { value: "pl", introducedIn: 1 },
      { value: "pt", introducedIn: 1 },
      { value: "ro", introducedIn: 1 },
      { value: "ru", introducedIn: 1 },
      { value: "sk", introducedIn: 1 },
      { value: "sl", introducedIn: 1 },
      { value: "es", introducedIn: 1 },
      { value: "sv", introducedIn: 1 },
      { value: "ta", introducedIn: 1 },
      { value: "te", introducedIn: 1 },
      { value: "th", introducedIn: 1 },
      { value: "tr", introducedIn: 1 },
      { value: "uk", introducedIn: 1 },
      { value: "vi", introducedIn: 1 },
    ],
  },
  playback_subtitle_languages: {
    type: "language_tag",
    options: [
      { value: "ar", introducedIn: 1 },
      { value: "bn", introducedIn: 1 },
      { value: "bg", introducedIn: 1 },
      { value: "zh", introducedIn: 1 },
      { value: "hr", introducedIn: 1 },
      { value: "cs", introducedIn: 1 },
      { value: "da", introducedIn: 1 },
      { value: "nl", introducedIn: 1 },
      { value: "en", introducedIn: 1 },
      { value: "fi", introducedIn: 1 },
      { value: "fr", introducedIn: 1 },
      { value: "de", introducedIn: 1 },
      { value: "el", introducedIn: 1 },
      { value: "he", introducedIn: 1 },
      { value: "hi", introducedIn: 1 },
      { value: "hu", introducedIn: 1 },
      { value: "id", introducedIn: 1 },
      { value: "it", introducedIn: 1 },
      { value: "ja", introducedIn: 1 },
      { value: "ko", introducedIn: 1 },
      { value: "ms", introducedIn: 1 },
      { value: "no", introducedIn: 1 },
      { value: "fa", introducedIn: 1 },
      { value: "pl", introducedIn: 1 },
      { value: "pt", introducedIn: 1 },
      { value: "ro", introducedIn: 1 },
      { value: "ru", introducedIn: 1 },
      { value: "sk", introducedIn: 1 },
      { value: "sl", introducedIn: 1 },
      { value: "es", introducedIn: 1 },
      { value: "sv", introducedIn: 1 },
      { value: "ta", introducedIn: 1 },
      { value: "te", introducedIn: 1 },
      { value: "th", introducedIn: 1 },
      { value: "tr", introducedIn: 1 },
      { value: "uk", introducedIn: 1 },
      { value: "vi", introducedIn: 1 },
    ],
  },
} as const satisfies Record<string, SettingOptionSet>;

export type SettingOptionSetId = keyof typeof SETTING_OPTION_SETS;

export const SETTING_KEYS = {
  /** Metadata language */
  CATALOG_METADATA_LANGUAGE: "catalog.metadata_language",
  /** Metadata language exceptions */
  CATALOG_METADATA_LANGUAGE_OVERRIDES: "catalog.metadata_language_overrides",
  /** Download quality */
  DOWNLOADS_DEFAULT_QUALITY: "downloads.default_quality",
  /** Keep watched downloads */
  DOWNLOADS_KEEP_WATCHED: "downloads.keep_watched",
  /** Download over Wi-Fi only */
  DOWNLOADS_WIFI_ONLY: "downloads.wifi_only",
  /** Primary menu */
  NAV_PRIMARY_MENU: "nav.primary_menu",
  /** Navigation shortcuts */
  NAV_SHORTCUTS: "nav.shortcuts",
  /** Show audiobooks */
  NAV_SHOW_AUDIOBOOKS: "nav.show_audiobooks",
  /** Preferred audio language */
  PLAYBACK_AUDIO_LANGUAGE: "playback.audio_language",
  /** Auto-play next episode */
  PLAYBACK_AUTO_PLAY_NEXT: "playback.auto_play_next",
  /** Preview next episode */
  PLAYBACK_AUTO_PLAY_NEXT_PREVIEW: "playback.auto_play_next_preview",
  /** Auto-skip credits */
  PLAYBACK_AUTO_SKIP_CREDITS: "playback.auto_skip_credits",
  /** Auto-skip intros */
  PLAYBACK_AUTO_SKIP_INTRO: "playback.auto_skip_intro",
  /** Auto-skip recaps */
  PLAYBACK_AUTO_SKIP_RECAP: "playback.auto_skip_recap",
  /** Skip intros */
  PLAYBACK_INTRO_SKIP_MODE: "playback.intro_skip_mode",
  /** Maximum bitrate */
  PLAYBACK_MAX_BITRATE_KBPS: "playback.max_bitrate_kbps",
  /** Next up prompt */
  PLAYBACK_NEXT_UP_PROMPT_SECONDS: "playback.next_up_prompt_seconds",
  /** Preferred quality */
  PLAYBACK_PREFERRED_QUALITY: "playback.preferred_quality",
  /** Show forced subtitles */
  PLAYBACK_SHOW_FORCED_SUBTITLES: "playback.show_forced_subtitles",
  /** Subtitle appearance */
  PLAYBACK_SUBTITLE_APPEARANCE: "playback.subtitle_appearance",
  /** Preferred subtitle language */
  PLAYBACK_SUBTITLE_LANGUAGE: "playback.subtitle_language",
  /** Subtitles */
  PLAYBACK_SUBTITLE_MODE: "playback.subtitle_mode",
  /** Audio sync offset */
  PLAYER_AUDIO_SYNC_MS: "player.audio_sync_ms",
  /** Dolby Vision */
  PLAYER_DOLBY_VISION_ENABLED: "player.dolby_vision_enabled",
  /** Dolby Vision Profile 7 fallback */
  PLAYER_DV_PROFILE7_HDR10_FALLBACK: "player.dv_profile7_hdr10_fallback",
  /** HDR */
  PLAYER_HDR_ENABLED: "player.hdr_enabled",
  /** Match content frame rate */
  PLAYER_MATCH_FRAME_RATE: "player.match_frame_rate",
  /** Screen orientation */
  PLAYER_ORIENTATION_MODE: "player.orientation_mode",
  /** Still watching prompt */
  PLAYER_PASSOUT_THRESHOLD: "player.passout_threshold",
  /** Picture in picture */
  PLAYER_PICTURE_IN_PICTURE_ENABLED: "player.picture_in_picture_enabled",
  /** Playback speed */
  PLAYER_PLAYBACK_SPEED: "player.playback_speed",
  /** Rewind on resume */
  PLAYER_RESUME_REWIND_SECONDS: "player.resume_rewind_seconds",
  /** Seek cache */
  PLAYER_SEEK_CACHE_ENABLED: "player.seek_cache_enabled",
  /** Default sleep timer */
  PLAYER_SLEEP_TIMER_DEFAULT_MINUTES: "player.sleep_timer_default_minutes",
  /** Subtitle sync offset */
  PLAYER_SUBTITLE_SYNC_MS: "player.subtitle_sync_ms",
  /** Video sizing */
  PLAYER_VIDEO_GRAVITY: "player.video_gravity",
  /** Search scope */
  SEARCH_MEDIA_SCOPE: "search.media_scope",
  /** Match device caption settings */
  SUBTITLE_MATCHES_DEVICE: "subtitle.matches_device",
  /** Poster badges */
  UI_CARD_OVERLAYS: "ui.card_overlays",
  /** Card overlays enabled */
  UI_CARD_OVERLAYS_ENABLED: "ui.card_overlays_enabled",
  /** Media cards */
  UI_CARD_PRESENTATION: "ui.card_presentation",
  /** Card quick actions */
  UI_CARD_QUICK_ACTIONS: "ui.card_quick_actions",
  /** Card quick actions enabled */
  UI_CARD_QUICK_ACTIONS_ENABLED: "ui.card_quick_actions_enabled",
  /** Custom CSS */
  UI_CUSTOM_CSS: "ui.custom_css",
  /** Custom theme variables */
  UI_CUSTOM_THEME_VARS: "ui.custom_theme_vars",
  /** Date format */
  UI_DATE_FORMAT: "ui.date_format",
  /** Hidden libraries */
  UI_DISABLED_LIBRARY_IDS: "ui.disabled_library_ids",
  /** High contrast */
  UI_HIGH_CONTRAST: "ui.high_contrast",
  /** Library order */
  UI_LIBRARY_ORDER: "ui.library_order",
  /** Remembered library view */
  UI_LIBRARY_PAGE_STATE: "ui.library_page_state",
  /** Next up episodes */
  UI_NEXT_UP_MODE: "ui.next_up_mode",
  /** Remember library view */
  UI_REMEMBER_LIBRARY_PAGE_STATE: "ui.remember_library_page_state",
  /** Pinned sidebar items */
  UI_SIDEBAR_PINS: "ui.sidebar_pins",
  /** Text size */
  UI_TEXT_SCALE: "ui.text_scale",
  /** Text weight */
  UI_TEXT_WEIGHT: "ui.text_weight",
  /** Theme */
  UI_THEME: "ui.theme",
  /** Time format */
  UI_TIME_FORMAT: "ui.time_format",
} as const;

export type SettingKey = (typeof SETTING_KEYS)[keyof typeof SETTING_KEYS];

export interface SettingDefinition {
  key: SettingKey;
  type: string;
  nullable: boolean;
  persistence: "remote" | "client_local";
  /** The manifest revision this definition first appeared in. A client
   * pinned to a newer contract than the server's advertised revision must
   * hide definitions, scopes, enum members and widened bounds introduced
   * after that revision — the server would reject them. */
  introducedIn: number;
  /** Superseded by another definition. The key still resolves and still
   * has to be readable, but a client must not offer it as a second control
   * beside its replacement — editing one would silently rewrite the other
   * through the server's compatibility mirror. */
  deprecated?: boolean;
  scopes: readonly string[];
  /** Revision each scope became writable at, aligned with scopes. */
  scopeIntroducedIn: readonly number[];
  resolutionOrder: readonly string[];
  defaultValue: unknown;
  label: string;
  description: string;
  category: string;
  control?: string;
  unit?: string;
  /** Advisory: platforms this setting is expected to matter on. Absent
   * means everywhere. A client hides settings for platforms it is not,
   * rather than disabling them without explanation. */
  platforms?: readonly string[];
  suggestedOptions?: SettingOptionSetId;
  unsetLabel?: string;
  values?: readonly { value: unknown; label: string; introducedIn: number }[];
  /** Present on enums whose members are ranked, so a ceiling or floor has a direction. */
  ordered?: boolean;
  minimum?: number;
  maximum?: number;
  /** Bound history, oldest first, when a bound was widened after revision 1;
   * a client filtering to an older server revision applies the newest entry
   * whose introducedIn does not exceed it. */
  minimumHistory?: readonly { value: number; introducedIn: number }[];
  maximumHistory?: readonly { value: number; introducedIn: number }[];
  step?: number;
  /** The policy input that narrows this setting, when the manifest binds one. */
  constrainedBy?: {
    policyInput: string;
    constraint: "ceiling" | "floor" | "allowlist" | "locked";
  };
}

export const SETTING_DEFINITIONS: Record<SettingKey, SettingDefinition> = {
  "catalog.metadata_language": {
    key: "catalog.metadata_language",
    type: "language_tag",
    nullable: true,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile", "default"],
    defaultValue: null,
    get label() {
      return tr("lib.settings_contract.metadata_language");
    },
    get description() {
      return tr(
        "lib.settings_contract.fallback_language_silo_prefers_for_titles_descriptions_and_artwork",
      );
    },
    category: "catalog",
    control: "select",
    suggestedOptions: "catalog_metadata_languages",
    unsetLabel: "lib.settings_contract.library_default",
  },
  "catalog.metadata_language_overrides": {
    key: "catalog.metadata_language_overrides",
    type: "object",
    nullable: false,
    persistence: "remote",
    introducedIn: 3,
    scopes: ["profile"],
    scopeIntroducedIn: [3],
    resolutionOrder: ["profile", "default"],
    defaultValue: {},
    get label() {
      return tr("lib.settings_contract.metadata_language_exceptions");
    },
    get description() {
      return tr(
        "lib.settings_contract.preferred_metadata_language_for_items_in_specific_original_languages",
      );
    },
    category: "catalog",
    control: "panel",
  },
  "downloads.default_quality": {
    key: "downloads.default_quality",
    type: "enum",
    nullable: false,
    persistence: "client_local",
    introducedIn: 1,
    scopes: ["client_local"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["client_local", "default"],
    defaultValue: "original",
    get label() {
      return tr("lib.settings_contract.download_quality");
    },
    get description() {
      return tr("lib.settings_contract.quality_preset_used_for_new_downloads");
    },
    category: "downloads",
    control: "select",
    platforms: ["ios", "android"],
    values: [
      {
        value: "1mbps",
        get label() {
          return tr("lib.settings_contract.value_1_mbps");
        },
        introducedIn: 1,
      },
      {
        value: "2mbps",
        get label() {
          return tr("lib.settings_contract.value_2_mbps");
        },
        introducedIn: 1,
      },
      {
        value: "5mbps",
        get label() {
          return tr("lib.settings_contract.value_5_mbps");
        },
        introducedIn: 1,
      },
      {
        value: "10mbps",
        get label() {
          return tr("lib.settings_contract.value_10_mbps");
        },
        introducedIn: 1,
      },
      {
        value: "20mbps",
        get label() {
          return tr("lib.settings_contract.value_20_mbps");
        },
        introducedIn: 1,
      },
      {
        value: "original",
        get label() {
          return tr("lib.settings_contract.original");
        },
        introducedIn: 1,
      },
    ],
    ordered: true,
  },
  "downloads.keep_watched": {
    key: "downloads.keep_watched",
    type: "boolean",
    nullable: false,
    persistence: "client_local",
    introducedIn: 1,
    scopes: ["client_local"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["client_local", "default"],
    defaultValue: false,
    get label() {
      return tr("lib.settings_contract.keep_watched_downloads");
    },
    get description() {
      return tr(
        "lib.settings_contract.do_not_suggest_reclaiming_space_from_downloads_you_have_finished",
      );
    },
    category: "downloads",
    control: "switch",
    platforms: ["ios", "android"],
  },
  "downloads.wifi_only": {
    key: "downloads.wifi_only",
    type: "boolean",
    nullable: false,
    persistence: "client_local",
    introducedIn: 1,
    scopes: ["client_local"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["client_local", "default"],
    defaultValue: true,
    get label() {
      return tr("lib.settings_contract.download_over_wi_fi_only");
    },
    get description() {
      return tr("lib.settings_contract.only_download_while_connected_to_wi_fi");
    },
    category: "downloads",
    control: "switch",
    platforms: ["ios", "android"],
  },
  "nav.primary_menu": {
    key: "nav.primary_menu",
    type: "object",
    nullable: true,
    persistence: "remote",
    introducedIn: 5,
    scopes: ["profile_client", "profile_device"],
    scopeIntroducedIn: [5, 5],
    resolutionOrder: ["profile_device", "profile_client", "default"],
    defaultValue: null,
    get label() {
      return tr("lib.settings_contract.primary_menu");
    },
    get description() {
      return tr("lib.settings_contract.the_ordered_visible_destinations_shared_by_like_clients");
    },
    category: "navigation",
    control: "panel",
    platforms: ["web", "ios", "tvos", "macos", "android", "android_tv"],
  },
  "nav.shortcuts": {
    key: "nav.shortcuts",
    type: "object",
    nullable: false,
    persistence: "remote",
    introducedIn: 5,
    scopes: ["profile"],
    scopeIntroducedIn: [5],
    resolutionOrder: ["profile", "default"],
    defaultValue: { items: [] },
    get label() {
      return tr("lib.settings_contract.navigation_shortcuts");
    },
    get description() {
      return tr(
        "lib.settings_contract.libraries_sections_and_collections_pinned_for_use_across_navigation_surfaces",
      );
    },
    category: "navigation",
  },
  "nav.show_audiobooks": {
    key: "nav.show_audiobooks",
    type: "boolean",
    nullable: false,
    persistence: "client_local",
    introducedIn: 1,
    scopes: ["client_local"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["client_local", "default"],
    defaultValue: false,
    get label() {
      return tr("lib.settings_contract.show_audiobooks");
    },
    get description() {
      return tr("lib.settings_contract.show_the_audiobooks_section_in_navigation");
    },
    category: "nav",
    control: "switch",
    platforms: ["ios", "tvos", "macos", "android", "android_tv"],
  },
  "playback.audio_language": {
    key: "playback.audio_language",
    type: "language_tag",
    nullable: true,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile", "profile_device", "profile_library", "profile_series"],
    scopeIntroducedIn: [1, 1, 1, 1],
    resolutionOrder: ["profile_series", "profile_library", "profile_device", "profile", "default"],
    defaultValue: null,
    get label() {
      return tr("lib.settings_contract.preferred_audio_language");
    },
    get description() {
      return tr("lib.settings_contract.choose_which_spoken_language_silo_should_prefer_first");
    },
    category: "playback",
    control: "select",
    suggestedOptions: "playback_audio_languages",
    unsetLabel: "lib.settings_contract.no_preference",
  },
  "playback.auto_play_next": {
    key: "playback.auto_play_next",
    type: "boolean",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile", "profile_device"],
    scopeIntroducedIn: [1, 1],
    resolutionOrder: ["profile_device", "profile", "default"],
    defaultValue: true,
    get label() {
      return tr("lib.settings_contract.auto_play_next_episode");
    },
    get description() {
      return tr("lib.settings_contract.continue_to_the_next_episode_automatically");
    },
    category: "playback",
    control: "switch",
  },
  "playback.auto_play_next_preview": {
    key: "playback.auto_play_next_preview",
    type: "boolean",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile", "profile_device"],
    scopeIntroducedIn: [1, 1],
    resolutionOrder: ["profile_device", "profile", "default"],
    defaultValue: false,
    get label() {
      return tr("lib.settings_contract.preview_next_episode");
    },
    get description() {
      return tr("lib.settings_contract.show_a_preview_of_the_next_episode_while_credits_play");
    },
    category: "playback",
    control: "switch",
  },
  "playback.auto_skip_credits": {
    key: "playback.auto_skip_credits",
    type: "boolean",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile", "profile_device"],
    scopeIntroducedIn: [1, 1],
    resolutionOrder: ["profile_device", "profile", "default"],
    defaultValue: false,
    get label() {
      return tr("lib.settings_contract.auto_skip_credits");
    },
    get description() {
      return tr(
        "lib.settings_contract.move_through_end_credits_automatically_when_a_skip_is_available",
      );
    },
    category: "playback",
    control: "switch",
  },
  "playback.auto_skip_intro": {
    key: "playback.auto_skip_intro",
    type: "boolean",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    deprecated: true,
    scopes: ["profile", "profile_device"],
    scopeIntroducedIn: [1, 1],
    resolutionOrder: ["profile_device", "profile", "default"],
    defaultValue: false,
    get label() {
      return tr("lib.settings_contract.auto_skip_intros");
    },
    get description() {
      return tr("lib.settings_contract.jump_past_intros_automatically_when_silo_can_detect_them");
    },
    category: "playback",
    control: "switch",
  },
  "playback.auto_skip_recap": {
    key: "playback.auto_skip_recap",
    type: "boolean",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile", "profile_device"],
    scopeIntroducedIn: [1, 1],
    resolutionOrder: ["profile_device", "profile", "default"],
    defaultValue: false,
    get label() {
      return tr("lib.settings_contract.auto_skip_recaps");
    },
    get description() {
      return tr(
        "lib.settings_contract.skip_previously_on_recaps_automatically_when_silo_can_detect_them",
      );
    },
    category: "playback",
    control: "switch",
  },
  "playback.intro_skip_mode": {
    key: "playback.intro_skip_mode",
    type: "enum",
    nullable: false,
    persistence: "remote",
    introducedIn: 7,
    scopes: ["profile", "profile_device"],
    scopeIntroducedIn: [7, 7],
    resolutionOrder: ["profile_device", "profile", "default"],
    defaultValue: "ask",
    get label() {
      return tr("lib.settings_contract.skip_intros");
    },
    get description() {
      return tr("lib.settings_contract.what_silo_does_when_an_intro_starts_leave_it_alone");
    },
    category: "playback",
    control: "select",
    values: [
      {
        value: "never",
        get label() {
          return tr("lib.settings_contract.never");
        },
        introducedIn: 7,
      },
      {
        value: "ask",
        get label() {
          return tr("lib.settings_contract.ask_to_skip");
        },
        introducedIn: 7,
      },
      {
        value: "always",
        get label() {
          return tr("lib.settings_contract.skip_automatically");
        },
        introducedIn: 7,
      },
    ],
  },
  "playback.max_bitrate_kbps": {
    key: "playback.max_bitrate_kbps",
    type: "integer",
    nullable: true,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile", "profile_device"],
    scopeIntroducedIn: [1, 1],
    resolutionOrder: ["profile_device", "profile", "default"],
    defaultValue: null,
    get label() {
      return tr("lib.settings_contract.maximum_bitrate");
    },
    get description() {
      return tr("lib.settings_contract.cap_how_much_bandwidth_playback_may_use_no_cap_means");
    },
    category: "playback",
    control: "select",
    unit: "kbps",
    minimum: 100,
    maximum: 200000,
  },
  "playback.next_up_prompt_seconds": {
    key: "playback.next_up_prompt_seconds",
    type: "integer",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile", "profile_device"],
    scopeIntroducedIn: [1, 1],
    resolutionOrder: ["profile_device", "profile", "default"],
    defaultValue: 30,
    get label() {
      return tr("lib.settings_contract.next_up_prompt");
    },
    get description() {
      return tr("lib.settings_contract.how_long_before_the_end_of_an_episode_the_next");
    },
    category: "playback",
    control: "slider",
    unit: "seconds",
    minimum: 0,
    maximum: 120,
  },
  "playback.preferred_quality": {
    key: "playback.preferred_quality",
    type: "enum",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile", "profile_device"],
    scopeIntroducedIn: [1, 1],
    resolutionOrder: ["profile_device", "profile", "default"],
    defaultValue: "auto",
    get label() {
      return tr("lib.settings_contract.preferred_quality");
    },
    get description() {
      return tr("lib.settings_contract.pick_the_quality_silo_should_prefer");
    },
    category: "playback",
    control: "select",
    values: [
      {
        value: "auto",
        get label() {
          return tr("lib.settings_contract.auto");
        },
        introducedIn: 1,
      },
      {
        value: "480p",
        get label() {
          return tr("lib.settings_contract.value_480p");
        },
        introducedIn: 1,
      },
      {
        value: "720p",
        get label() {
          return tr("lib.settings_contract.value_720p");
        },
        introducedIn: 1,
      },
      {
        value: "1080p",
        get label() {
          return tr("lib.settings_contract.value_1080p");
        },
        introducedIn: 1,
      },
      {
        value: "2160p",
        get label() {
          return tr("lib.settings_contract.value_2160p_4_k");
        },
        introducedIn: 1,
      },
      {
        value: "original",
        get label() {
          return tr("lib.settings_contract.original_quality");
        },
        introducedIn: 1,
      },
    ],
    ordered: true,
    constrainedBy: { policyInput: "max_playback_quality", constraint: "ceiling" },
  },
  "playback.show_forced_subtitles": {
    key: "playback.show_forced_subtitles",
    type: "boolean",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile", "profile_device", "profile_library", "profile_series"],
    scopeIntroducedIn: [1, 1, 1, 1],
    resolutionOrder: ["profile_series", "profile_library", "profile_device", "profile", "default"],
    defaultValue: true,
    get label() {
      return tr("lib.settings_contract.show_forced_subtitles");
    },
    get description() {
      return tr(
        "lib.settings_contract.show_subtitles_for_foreign_language_dialogue_even_when_subtitles_are",
      );
    },
    category: "playback",
    control: "switch",
  },
  "playback.subtitle_appearance": {
    key: "playback.subtitle_appearance",
    type: "object",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile", "profile_device"],
    scopeIntroducedIn: [1, 1],
    resolutionOrder: ["profile_device", "profile", "default"],
    defaultValue: {
      fontSize: "large",
      fontFamily: "sans-serif",
      fontColor: "#ffffff",
      backgroundColor: "#000000",
      backgroundStyle: "box",
      backgroundOpacity: 75,
      textOutline: false,
      textOutlineColor: "#000000",
      position: "bottom",
    },
    get label() {
      return tr("lib.settings_contract.subtitle_appearance");
    },
    get description() {
      return tr("lib.settings_contract.how_subtitles_are_drawn_during_playback");
    },
    category: "playback",
    control: "panel",
  },
  "playback.subtitle_language": {
    key: "playback.subtitle_language",
    type: "language_tag",
    nullable: true,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile", "profile_device", "profile_library", "profile_series"],
    scopeIntroducedIn: [1, 1, 1, 1],
    resolutionOrder: ["profile_series", "profile_library", "profile_device", "profile", "default"],
    defaultValue: null,
    get label() {
      return tr("lib.settings_contract.preferred_subtitle_language");
    },
    get description() {
      return tr("lib.settings_contract.choose_which_subtitle_language_silo_should_prefer_first");
    },
    category: "playback",
    control: "select",
    suggestedOptions: "playback_subtitle_languages",
    unsetLabel: "lib.settings_contract.none",
  },
  "playback.subtitle_mode": {
    key: "playback.subtitle_mode",
    type: "enum",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile", "profile_device", "profile_library", "profile_series"],
    scopeIntroducedIn: [1, 1, 1, 1],
    resolutionOrder: ["profile_series", "profile_library", "profile_device", "profile", "default"],
    defaultValue: "auto",
    get label() {
      return tr("lib.settings_contract.subtitles");
    },
    get description() {
      return tr("lib.settings_contract.when_silo_should_turn_subtitles_on");
    },
    category: "playback",
    control: "select",
    values: [
      {
        value: "auto",
        get label() {
          return tr("lib.settings_contract.auto");
        },
        introducedIn: 1,
      },
      {
        value: "always",
        get label() {
          return tr("lib.settings_contract.always_on");
        },
        introducedIn: 1,
      },
      {
        value: "off",
        get label() {
          return tr("lib.settings_contract.off");
        },
        introducedIn: 1,
      },
    ],
  },
  "player.audio_sync_ms": {
    key: "player.audio_sync_ms",
    type: "integer",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile_device"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile_device", "default"],
    defaultValue: 0,
    get label() {
      return tr("lib.settings_contract.audio_sync_offset");
    },
    get description() {
      return tr("lib.settings_contract.shift_audio_earlier_or_later_to_correct_lip_sync_on");
    },
    category: "player",
    control: "slider",
    unit: "milliseconds",
    platforms: ["ios", "tvos", "macos", "android", "android_tv"],
    minimum: -5000,
    maximum: 5000,
  },
  "player.dolby_vision_enabled": {
    key: "player.dolby_vision_enabled",
    type: "boolean",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile_device"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile_device", "default"],
    defaultValue: true,
    get label() {
      return tr("lib.settings_contract.dolby_vision");
    },
    get description() {
      return tr("lib.settings_contract.allow_dolby_vision_output_on_this_device");
    },
    category: "player",
    control: "switch",
    platforms: ["ios", "tvos", "macos", "android", "android_tv"],
  },
  "player.dv_profile7_hdr10_fallback": {
    key: "player.dv_profile7_hdr10_fallback",
    type: "boolean",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile_device"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile_device", "default"],
    defaultValue: false,
    get label() {
      return tr("lib.settings_contract.dolby_vision_profile_7_fallback");
    },
    get description() {
      return tr("lib.settings_contract.play_profile_7_sources_as_hdr10_when_this_device_cannot");
    },
    category: "player",
    control: "switch",
    platforms: ["ios", "tvos", "macos", "android", "android_tv"],
  },
  "player.hdr_enabled": {
    key: "player.hdr_enabled",
    type: "boolean",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile_device"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile_device", "default"],
    defaultValue: true,
    get label() {
      return tr("lib.settings_contract.hdr");
    },
    get description() {
      return tr("lib.settings_contract.allow_hdr_output_on_this_device");
    },
    category: "player",
    control: "switch",
  },
  "player.match_frame_rate": {
    key: "player.match_frame_rate",
    type: "boolean",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile_device"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile_device", "default"],
    defaultValue: false,
    get label() {
      return tr("lib.settings_contract.match_content_frame_rate");
    },
    get description() {
      return tr("lib.settings_contract.switch_the_display_refresh_rate_to_match_what_is_playing");
    },
    category: "player",
    control: "switch",
    platforms: ["android", "android_tv", "tvos"],
  },
  "player.orientation_mode": {
    key: "player.orientation_mode",
    type: "enum",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile_device"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile_device", "default"],
    defaultValue: "landscapeLocked",
    get label() {
      return tr("lib.settings_contract.screen_orientation");
    },
    get description() {
      return tr("lib.settings_contract.whether_the_player_rotates_with_the_device");
    },
    category: "player",
    control: "select",
    platforms: ["ios", "android"],
    values: [
      {
        value: "landscapeLocked",
        get label() {
          return tr("lib.settings_contract.landscape");
        },
        introducedIn: 1,
      },
      {
        value: "rotateFreely",
        get label() {
          return tr("lib.settings_contract.rotate_freely");
        },
        introducedIn: 1,
      },
    ],
  },
  "player.passout_threshold": {
    key: "player.passout_threshold",
    type: "integer",
    nullable: false,
    persistence: "client_local",
    introducedIn: 1,
    scopes: ["client_local"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["client_local", "default"],
    defaultValue: 3,
    get label() {
      return tr("lib.settings_contract.still_watching_prompt");
    },
    get description() {
      return tr("lib.settings_contract.how_many_episodes_auto_play_before_silo_asks_whether_you");
    },
    category: "player",
    control: "stepper",
    unit: "episodes",
    platforms: ["ios", "tvos", "macos", "android", "android_tv", "web"],
    minimum: 0,
    maximum: 20,
  },
  "player.picture_in_picture_enabled": {
    key: "player.picture_in_picture_enabled",
    type: "boolean",
    nullable: false,
    persistence: "client_local",
    introducedIn: 1,
    scopes: ["client_local"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["client_local", "default"],
    defaultValue: true,
    get label() {
      return tr("lib.settings_contract.picture_in_picture");
    },
    get description() {
      return tr("lib.settings_contract.keep_playing_in_a_floating_window_when_you_leave_the");
    },
    category: "player",
    control: "switch",
    platforms: ["ios", "macos", "android"],
  },
  "player.playback_speed": {
    key: "player.playback_speed",
    type: "number",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile_device"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile_device", "default"],
    defaultValue: 1.0,
    get label() {
      return tr("lib.settings_contract.playback_speed");
    },
    get description() {
      return tr("lib.settings_contract.default_playback_speed_on_this_device");
    },
    category: "player",
    control: "slider",
    unit: "x",
    minimum: 0.25,
    maximum: 3,
    step: 0.05,
  },
  "player.resume_rewind_seconds": {
    key: "player.resume_rewind_seconds",
    type: "integer",
    nullable: false,
    persistence: "client_local",
    introducedIn: 1,
    scopes: ["client_local"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["client_local", "default"],
    defaultValue: 7,
    get label() {
      return tr("lib.settings_contract.rewind_on_resume");
    },
    get description() {
      return tr("lib.settings_contract.skip_back_this_far_when_resuming_a_partly_watched_item");
    },
    category: "player",
    control: "stepper",
    unit: "seconds",
    platforms: ["ios", "tvos", "macos", "android", "android_tv", "web"],
    minimum: 0,
    maximum: 30,
  },
  "player.seek_cache_enabled": {
    key: "player.seek_cache_enabled",
    type: "boolean",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile_device"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile_device", "default"],
    defaultValue: true,
    get label() {
      return tr("lib.settings_contract.seek_cache");
    },
    get description() {
      return tr("lib.settings_contract.keep_recently_played_segments_buffered_for_faster_seeking");
    },
    category: "player",
    control: "switch",
  },
  "player.sleep_timer_default_minutes": {
    key: "player.sleep_timer_default_minutes",
    type: "integer",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile_device"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile_device", "default"],
    defaultValue: 30,
    get label() {
      return tr("lib.settings_contract.default_sleep_timer");
    },
    get description() {
      return tr("lib.settings_contract.duration_the_sleep_timer_starts_on_when_you_turn_it");
    },
    category: "player",
    control: "stepper",
    unit: "minutes",
    minimum: 0,
    maximum: 240,
  },
  "player.subtitle_sync_ms": {
    key: "player.subtitle_sync_ms",
    type: "integer",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile_device"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile_device", "default"],
    defaultValue: 0,
    get label() {
      return tr("lib.settings_contract.subtitle_sync_offset");
    },
    get description() {
      return tr("lib.settings_contract.shift_subtitles_earlier_or_later_on_this_device");
    },
    category: "player",
    control: "slider",
    unit: "milliseconds",
    minimum: -10000,
    maximum: 10000,
  },
  "player.video_gravity": {
    key: "player.video_gravity",
    type: "enum",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile_device"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile_device", "default"],
    defaultValue: "fit",
    get label() {
      return tr("lib.settings_contract.video_sizing");
    },
    get description() {
      return tr("lib.settings_contract.how_video_fills_the_screen_on_this_device");
    },
    category: "player",
    control: "select",
    values: [
      {
        value: "fit",
        get label() {
          return tr("lib.settings_contract.fit");
        },
        introducedIn: 1,
      },
      {
        value: "fill",
        get label() {
          return tr("lib.settings_contract.fill");
        },
        introducedIn: 1,
      },
      {
        value: "stretch",
        get label() {
          return tr("lib.settings_contract.stretch");
        },
        introducedIn: 1,
      },
    ],
  },
  "search.media_scope": {
    key: "search.media_scope",
    type: "enum",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile", "default"],
    defaultValue: "video",
    get label() {
      return tr("lib.settings_contract.search_scope");
    },
    get description() {
      return tr("lib.settings_contract.what_search_covers_by_default");
    },
    category: "search",
    control: "select",
    values: [
      {
        value: "all",
        get label() {
          return tr("lib.settings_contract.everything");
        },
        introducedIn: 1,
      },
      {
        value: "video",
        get label() {
          return tr("lib.settings_contract.movies_and_series");
        },
        introducedIn: 1,
      },
      {
        value: "audiobook",
        get label() {
          return tr("lib.settings_contract.audiobooks");
        },
        introducedIn: 1,
      },
    ],
  },
  "subtitle.matches_device": {
    key: "subtitle.matches_device",
    type: "boolean",
    nullable: false,
    persistence: "client_local",
    introducedIn: 1,
    scopes: ["client_local"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["client_local", "default"],
    defaultValue: false,
    get label() {
      return tr("lib.settings_contract.match_device_caption_settings");
    },
    get description() {
      return tr("lib.settings_contract.use_the_operating_system_s_caption_style_instead_of_silo");
    },
    category: "playback",
    control: "switch",
    platforms: ["ios", "tvos", "macos", "android", "android_tv"],
  },
  "ui.card_overlays": {
    key: "ui.card_overlays",
    type: "object",
    nullable: true,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile", "default"],
    defaultValue: null,
    get label() {
      return tr("lib.settings_contract.poster_badges");
    },
    get description() {
      return tr("lib.settings_contract.which_badges_appear_on_poster_cards_and_where");
    },
    category: "appearance",
    platforms: ["web", "ios", "tvos", "macos", "android", "android_tv"],
  },
  "ui.card_overlays_enabled": {
    key: "ui.card_overlays_enabled",
    type: "boolean",
    nullable: true,
    persistence: "remote",
    introducedIn: 8,
    scopes: ["profile"],
    scopeIntroducedIn: [8],
    resolutionOrder: ["profile", "default"],
    defaultValue: null,
    get label() {
      return tr("lib.settings_contract.card_overlays_enabled");
    },
    get description() {
      return tr("lib.settings_contract.show_overlay_badges_on_media_cards");
    },
    category: "appearance",
    control: "switch",
    platforms: ["web"],
  },
  "ui.card_presentation": {
    key: "ui.card_presentation",
    type: "object",
    nullable: false,
    persistence: "remote",
    introducedIn: 5,
    scopes: ["profile", "profile_client", "profile_device"],
    scopeIntroducedIn: [5, 5, 5],
    resolutionOrder: ["profile_device", "profile_client", "profile", "default"],
    defaultValue: { poster_size: "standard", caption: "title_metadata" },
    get label() {
      return tr("lib.settings_contract.media_cards");
    },
    get description() {
      return tr("lib.settings_contract.poster_size_and_caption_detail_used_by_media_cards");
    },
    category: "appearance",
    control: "panel",
    platforms: ["web", "ios", "tvos", "macos", "android", "android_tv"],
  },
  "ui.card_quick_actions": {
    key: "ui.card_quick_actions",
    type: "enum",
    nullable: true,
    persistence: "remote",
    introducedIn: 8,
    scopes: ["profile"],
    scopeIntroducedIn: [8],
    resolutionOrder: ["profile", "default"],
    defaultValue: null,
    get label() {
      return tr("lib.settings_contract.card_quick_actions");
    },
    get description() {
      return tr("lib.settings_contract.which_favorite_and_watched_shortcuts_appear_on_media_cards");
    },
    category: "appearance",
    control: "select",
    platforms: ["web"],
    values: [
      {
        value: "both",
        get label() {
          return tr("lib.settings_contract.both");
        },
        introducedIn: 8,
      },
      {
        value: "favorites",
        get label() {
          return tr("lib.settings_contract.favorites_only");
        },
        introducedIn: 8,
      },
      {
        value: "watched",
        get label() {
          return tr("lib.settings_contract.watch_indicator_only");
        },
        introducedIn: 8,
      },
    ],
  },
  "ui.card_quick_actions_enabled": {
    key: "ui.card_quick_actions_enabled",
    type: "boolean",
    nullable: true,
    persistence: "remote",
    introducedIn: 8,
    scopes: ["profile"],
    scopeIntroducedIn: [8],
    resolutionOrder: ["profile", "default"],
    defaultValue: null,
    get label() {
      return tr("lib.settings_contract.card_quick_actions_enabled");
    },
    get description() {
      return tr(
        "lib.settings_contract.show_the_selected_favorite_and_watched_shortcuts_on_media_cards",
      );
    },
    category: "appearance",
    control: "switch",
    platforms: ["web"],
  },
  "ui.custom_css": {
    key: "ui.custom_css",
    type: "string",
    nullable: true,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile", "default"],
    defaultValue: null,
    get label() {
      return tr("lib.settings_contract.custom_css");
    },
    get description() {
      return tr("lib.settings_contract.raw_css_applied_on_top_of_the_selected_theme");
    },
    category: "appearance",
    control: "text",
    platforms: ["web"],
  },
  "ui.custom_theme_vars": {
    key: "ui.custom_theme_vars",
    type: "object",
    nullable: true,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile", "default"],
    defaultValue: null,
    get label() {
      return tr("lib.settings_contract.custom_theme_variables");
    },
    get description() {
      return tr("lib.settings_contract.per_token_overrides_applied_on_top_of_the_selected_theme");
    },
    category: "appearance",
    control: "panel",
    platforms: ["web"],
  },
  "ui.date_format": {
    key: "ui.date_format",
    type: "enum",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile", "default"],
    defaultValue: "auto",
    get label() {
      return tr("lib.settings_contract.date_format");
    },
    get description() {
      return tr("lib.settings_contract.how_dates_are_written_across_the_interface");
    },
    category: "appearance",
    control: "select",
    values: [
      {
        value: "auto",
        get label() {
          return tr("lib.settings_contract.match_device");
        },
        introducedIn: 1,
      },
      { value: "DD/MM/YYYY", label: "", introducedIn: 1 },
      { value: "MM/DD/YYYY", label: "", introducedIn: 1 },
      { value: "YYYY-MM-DD", label: "", introducedIn: 1 },
    ],
  },
  "ui.disabled_library_ids": {
    key: "ui.disabled_library_ids",
    type: "object",
    nullable: true,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile", "default"],
    defaultValue: null,
    get label() {
      return tr("lib.settings_contract.hidden_libraries");
    },
    get description() {
      return tr("lib.settings_contract.libraries_you_have_hidden_from_your_own_browsing");
    },
    category: "navigation",
  },
  "ui.high_contrast": {
    key: "ui.high_contrast",
    type: "boolean",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile", "profile_device"],
    scopeIntroducedIn: [1, 1],
    resolutionOrder: ["profile_device", "profile", "default"],
    defaultValue: false,
    get label() {
      return tr("lib.settings_contract.high_contrast");
    },
    get description() {
      return tr("lib.settings_contract.increase_contrast_across_the_interface");
    },
    category: "appearance",
    control: "switch",
    platforms: ["web"],
  },
  "ui.library_order": {
    key: "ui.library_order",
    type: "object",
    nullable: true,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile", "default"],
    defaultValue: null,
    get label() {
      return tr("lib.settings_contract.library_order");
    },
    get description() {
      return tr("lib.settings_contract.the_order_your_libraries_appear_in");
    },
    category: "navigation",
  },
  "ui.library_page_state": {
    key: "ui.library_page_state",
    type: "object",
    nullable: true,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile_device"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile_device", "default"],
    defaultValue: null,
    get label() {
      return tr("lib.settings_contract.remembered_library_view");
    },
    get description() {
      return tr("lib.settings_contract.saved_browse_state_for_each_library");
    },
    category: "navigation",
    platforms: ["web"],
  },
  "ui.next_up_mode": {
    key: "ui.next_up_mode",
    type: "enum",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile", "default"],
    defaultValue: "combined",
    get label() {
      return tr("lib.settings_contract.next_up_episodes");
    },
    get description() {
      return tr(
        "lib.settings_contract.whether_upcoming_episodes_stay_with_continue_watching_or_get_their",
      );
    },
    category: "navigation",
    control: "select",
    values: [
      {
        value: "combined",
        get label() {
          return tr("lib.settings_contract.with_continue_watching");
        },
        introducedIn: 1,
      },
      {
        value: "separate",
        get label() {
          return tr("lib.settings_contract.separate_row");
        },
        introducedIn: 1,
      },
    ],
  },
  "ui.remember_library_page_state": {
    key: "ui.remember_library_page_state",
    type: "boolean",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile_device"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile_device", "default"],
    defaultValue: true,
    get label() {
      return tr("lib.settings_contract.remember_library_view");
    },
    get description() {
      return tr("lib.settings_contract.return_to_where_you_left_off_when_reopening_a_library");
    },
    category: "navigation",
    control: "switch",
    platforms: ["web"],
  },
  "ui.sidebar_pins": {
    key: "ui.sidebar_pins",
    type: "object",
    nullable: true,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile", "default"],
    defaultValue: null,
    get label() {
      return tr("lib.settings_contract.pinned_sidebar_items");
    },
    get description() {
      return tr("lib.settings_contract.sections_and_collections_pinned_into_the_sidebar");
    },
    category: "navigation",
    platforms: ["web"],
  },
  "ui.text_scale": {
    key: "ui.text_scale",
    type: "enum",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile", "profile_device"],
    scopeIntroducedIn: [1, 1],
    resolutionOrder: ["profile_device", "profile", "default"],
    defaultValue: "default",
    get label() {
      return tr("lib.settings_contract.text_size");
    },
    get description() {
      return tr("lib.settings_contract.overall_interface_text_size");
    },
    category: "appearance",
    control: "select",
    platforms: ["web"],
    values: [
      {
        value: "default",
        get label() {
          return tr("lib.settings_contract.default");
        },
        introducedIn: 1,
      },
      {
        value: "large",
        get label() {
          return tr("lib.settings_contract.large");
        },
        introducedIn: 1,
      },
      {
        value: "x-large",
        get label() {
          return tr("lib.settings_contract.extra_large");
        },
        introducedIn: 1,
      },
    ],
    ordered: true,
  },
  "ui.text_weight": {
    key: "ui.text_weight",
    type: "enum",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile", "profile_device"],
    scopeIntroducedIn: [1, 1],
    resolutionOrder: ["profile_device", "profile", "default"],
    defaultValue: "default",
    get label() {
      return tr("lib.settings_contract.text_weight");
    },
    get description() {
      return tr("lib.settings_contract.use_heavier_interface_text_for_readability");
    },
    category: "appearance",
    control: "select",
    platforms: ["web"],
    values: [
      {
        value: "default",
        get label() {
          return tr("lib.settings_contract.default");
        },
        introducedIn: 1,
      },
      {
        value: "strong",
        get label() {
          return tr("lib.settings_contract.bolder");
        },
        introducedIn: 1,
      },
    ],
  },
  "ui.theme": {
    key: "ui.theme",
    type: "enum",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile", "profile_device"],
    scopeIntroducedIn: [1, 1],
    resolutionOrder: ["profile_device", "profile", "default"],
    defaultValue: "midnight-cinema",
    get label() {
      return tr("lib.settings_contract.theme");
    },
    get description() {
      return tr("lib.settings_contract.colour_theme_for_the_silo_interface");
    },
    category: "appearance",
    control: "select",
    platforms: ["web"],
    values: [
      {
        value: "midnight-cinema",
        get label() {
          return tr("lib.settings_contract.midnight_cinema");
        },
        introducedIn: 1,
      },
      {
        value: "cinema-light",
        get label() {
          return tr("lib.settings_contract.cinema_light");
        },
        introducedIn: 1,
      },
      {
        value: "cobalt-studio",
        get label() {
          return tr("lib.settings_contract.cobalt_studio");
        },
        introducedIn: 1,
      },
      {
        value: "oxblood-noir",
        get label() {
          return tr("lib.settings_contract.oxblood_noir");
        },
        introducedIn: 1,
      },
      {
        value: "evergreen-studio",
        get label() {
          return tr("lib.settings_contract.evergreen_studio");
        },
        introducedIn: 1,
      },
    ],
  },
  "ui.time_format": {
    key: "ui.time_format",
    type: "enum",
    nullable: false,
    persistence: "remote",
    introducedIn: 1,
    scopes: ["profile"],
    scopeIntroducedIn: [1],
    resolutionOrder: ["profile", "default"],
    defaultValue: "auto",
    get label() {
      return tr("lib.settings_contract.time_format");
    },
    get description() {
      return tr("lib.settings_contract.how_clock_times_are_written_across_the_interface");
    },
    category: "appearance",
    control: "select",
    values: [
      {
        value: "auto",
        get label() {
          return tr("lib.settings_contract.match_device");
        },
        introducedIn: 1,
      },
      {
        value: "12h",
        get label() {
          return tr("lib.settings_contract.value_12_hour");
        },
        introducedIn: 1,
      },
      {
        value: "24h",
        get label() {
          return tr("lib.settings_contract.value_24_hour");
        },
        introducedIn: 1,
      },
    ],
  },
};
